/// Pure-Dart, UI-independent camera-access API. No `package:flutter` dependency — see
/// design/stages/mobile-app-android-1-video-image-pipeline/DESIGN.md §2/§3. Both the app's UI
/// layer and, later, an in-app agent's tool registry are equal consumers of this package.
///
/// `lib/src/` layout (restructured 2026-08-11 for a cleaner hand-off surface — see
/// `kb/raw/2026-08-11-code-camera-api-lan-wan-restructure.md`):
///   - `camera_connection.dart`, `camera_result.dart` — shared by every client on both
///     transports, so they live at the root rather than under `lan/` or `wan/`.
///   - `night_vision_types.dart`, `mirror_flip_types.dart`, `privacy_mode_types.dart` — wire
///     enums + (for night vision) the transport-agnostic `NightVisionSource` interface, shared
///     by the matching `lan/nuraeye/*` and `wan/wan_*` client pair for that setting.
///   - `util/` — pure math/data helpers with no network call of any kind.
///   - `lan/onvif/` — ONVIF SOAP clients.
///   - `lan/nuraeye/` — the proprietary `/nuraeye/*` REST API: `NuraeyeClient` (hand-written,
///     what every other class here actually calls through) plus every `rest_*.dart` file
///     (machine-generated by `tools/generate_dart_rest_client.py`, currently unused by
///     `NuraeyeClient` — see that script's own doc for why both still exist).
///   - `lan/discovery/` — WS-Discovery (UDP multicast device discovery, not SOAP or REST).
///   - `wan/` — AWS IoT MQTT command relay + KVS playback, mirroring `lan/nuraeye/`'s settings
///     one-for-one where a WAN counterpart exists.
library;

export 'src/anti_flicker_types.dart';
export 'src/camera_connection.dart';
export 'src/camera_result.dart';
export 'src/device_reset_types.dart';
export 'src/lan/discovery/ws_discovery_client.dart';
export 'src/lan/insecure_camera_http_client.dart';
export 'src/lan/nuraeye/event_preferences_client.dart';
export 'src/lan/nuraeye/event_response_actions_client.dart';
export 'src/lan/nuraeye/anti_flicker_client.dart';
export 'src/lan/nuraeye/audio_volume_client.dart';
export 'src/lan/nuraeye/capabilities_client.dart';
export 'src/lan/nuraeye/cloud_streaming_client.dart';
export 'src/lan/nuraeye/mirror_flip_client.dart';
export 'src/lan/nuraeye/network_info_client.dart';
export 'src/lan/nuraeye/night_vision_client.dart';
export 'src/lan/nuraeye/nuraeye_client.dart';
export 'src/lan/nuraeye/privacy_mode_client.dart';
export 'src/lan/nuraeye/snapshot_client.dart';
export 'src/lan/nuraeye/webrtc_uri_client.dart';
// ---- BEGIN GENERATED (tools/generate_dart_rest_client.py) — DO NOT HAND-EDIT ----
export 'src/lan/nuraeye/nuraeye_rest_client.dart';
export 'src/lan/nuraeye/rest_alerts_client.dart';
export 'src/lan/nuraeye/rest_audio_client.dart';
export 'src/lan/nuraeye/rest_capabilities_client.dart';
export 'src/lan/nuraeye/rest_deterrence_alarms_client.dart';
export 'src/lan/nuraeye/rest_identity_discovery_client.dart';
export 'src/lan/nuraeye/rest_network_connectivity_client.dart';
export 'src/lan/nuraeye/rest_privacy_client.dart';
export 'src/lan/nuraeye/rest_result.dart';
export 'src/lan/nuraeye/rest_storage_client.dart';
export 'src/lan/nuraeye/rest_streaming_client.dart';
export 'src/lan/nuraeye/rest_video_image_client.dart';
// ---- END GENERATED ----
export 'src/lan/onvif/audio_capability_client.dart';
export 'src/lan/onvif/mask_client.dart';
export 'src/lan/onvif/media2_capabilities_client.dart';
export 'src/lan/onvif/onvif_device_client.dart';
export 'src/lan/onvif/onvif_imaging_client.dart';
export 'src/lan/onvif/onvif_video_encoder_client.dart';
export 'src/lan/onvif/osd_client.dart';
export 'src/lan/onvif/speaker_volume_client.dart';
export 'src/lan/wsse_digest.dart';
export 'src/mirror_flip_types.dart';
export 'src/night_vision_types.dart';
export 'src/privacy_mode_types.dart';
export 'src/util/onvif_rect_coordinates.dart';
export 'src/wan/aws_wan_live_view_client.dart';
export 'src/wan/iot_command_client.dart';
export 'src/wan/kvs_playback_client.dart';
export 'src/wan/wan_auth.dart';
export 'src/wan/wan_audio_volume_client.dart';
export 'src/wan/wan_device_identity_client.dart';
export 'src/wan/wan_image_quality_client.dart';
export 'src/wan/wan_imaging_client.dart';
export 'src/wan/wan_live_view_client.dart';
export 'src/wan/wan_mask_client.dart';
export 'src/wan/wan_event_preferences_client.dart';
export 'src/wan/wan_event_response_actions_client.dart';
export 'src/wan/wan_anti_flicker_client.dart';
export 'src/wan/wan_mirror_flip_client.dart';
export 'src/wan/wan_night_vision_client.dart';
export 'src/wan/wan_osd_client.dart';
export 'src/wan/wan_preview_snapshot_client.dart';
export 'src/wan/wan_privacy_mode_client.dart';
export 'src/wan/wan_speaker_volume_client.dart';
export 'src/wan/wan_video_encoder_client.dart';
